module "azure"{
   source = "module"
   os_version = "${var.os_version}"         
   offer  = "${var.offer}"
   vm2_computername = "${var.vm2_computername}"
   vm_size = "${var.vm_size}"
   sku  = "${var.sku}"
   private_subnet2_range = "${var.private_subnet2_range}"
   admin_username = "${var.admin_username}"
   location = "${var.location}"
   vnet_name = "${var.vnet_name}"
   resource_group_name = "${var.resource_group_name}"
   publisher = "${var.publisher}"
   ssh_pub_key = "${var.ssh_pub_key}"
   security_group_name = "${var.security_group_name}"
   environment = "${var.environment}"
   private_subnet3_range = "${var.private_subnet3_range}"
   vm3_computername = "${var.vm3_computername}"
   private_subnet1_range = "${var.private_subnet1_range}"
   address_space = "${var.address_space}"
   vm1_computername = "${var.vm1_computername}"
}
