variable "instance_type" {}
variable "key_name" {}
variable "virginia_vpc_id" {}
variable "user" {}
variable "ssh_key_location" {}
variable "zone_id" {}
variable "domain" {}
variable "region" {}
variable "virginia" {}
variable "oregon" {}
variable "oregon_vpc_id" {}
