location                =   "westus2"
address_space           =   "10.0.0.0/16"
vnet_name               =   "dev1"
environment             =   "dev"
resource_group_name     =   "dev"        #Precreate this while creating Backend Container
security_group_name     =   "sec_group1"
ssh_key                 =   "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBtMReX6tHOlpbyR2Ed3/bkemqBmrCSPhF/BPMWdzGX2353TIGfplD91Z1FtDjCbKbni0zdIbnaKJUyN+86LSliMQ+bHrOIIbR+bXRsZRIFyKaCAE4Za1ymKrP0u9w04flAa+U0/5aVERCDALjVnYXoCXtf7HK/sSimj2yJYuUsm8Cy/ldAY+idcw/Yg5IoAUExXdrWLRldfTcyxOzfjKd3xG0x1MydxaA+POFYfmWgTSv6SijcO1zwbjuyuI/nLHmIV8+76aE6Jkp0G/Kr1b0UBtanmkm2kY23lzMGx2wlk0Vq8UP+wQFkyvjBUQvnxi8o+BQuARd/9EsnNgfB8qH root@ip-172-31-19-165.eu-west-2.compute.internal"
vm1_computername        =   "vm1"
vm2_computername        =   "vm2"
vm3_computername        =   "vm3"
private_subnet1_range   =   "10.0.1.0/24"
private_subnet2_range   =   "10.0.2.0/24"
private_subnet3_range   =   "10.0.3.0/24"

#OS Information
publisher               =   "OpenLogic"
offer                   =   "CentOS"
sku                     =   "7.5"
version                 =   "latest"
admin_username          =   "centos"
vm_size                 =   "Standard_DS1_v2"
storage_account         =   "dev1storageaccount1"
